// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Debug.proto

package com.dji.TigerApp.protobuf;

public interface DebugMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dji.TigerApp.protobuf.DebugMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msg = 1;</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 1;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
