// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Debug.proto

package com.dji.TigerApp.protobuf;

public final class Debug {
  private Debug() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dji_TigerApp_protobuf_DebugMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dji_TigerApp_protobuf_DebugMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Debug.proto\022\031com.dji.TigerApp.protobuf" +
      "\"\033\n\014DebugMessage\022\013\n\003msg\030\001 \001(\tB\035\n\031com.dji" +
      ".TigerApp.protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_dji_TigerApp_protobuf_DebugMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_dji_TigerApp_protobuf_DebugMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dji_TigerApp_protobuf_DebugMessage_descriptor,
        new java.lang.String[] { "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
