// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Route.proto

package com.dji.TigerApp.protobuf;

public interface RouteArrayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.RouteArray)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tutorial.RoutePoint waypoints = 1;</code>
   */
  java.util.List<com.dji.TigerApp.protobuf.RoutePoint> 
      getWaypointsList();
  /**
   * <code>repeated .tutorial.RoutePoint waypoints = 1;</code>
   */
  com.dji.TigerApp.protobuf.RoutePoint getWaypoints(int index);
  /**
   * <code>repeated .tutorial.RoutePoint waypoints = 1;</code>
   */
  int getWaypointsCount();
  /**
   * <code>repeated .tutorial.RoutePoint waypoints = 1;</code>
   */
  java.util.List<? extends com.dji.TigerApp.protobuf.RoutePointOrBuilder> 
      getWaypointsOrBuilderList();
  /**
   * <code>repeated .tutorial.RoutePoint waypoints = 1;</code>
   */
  com.dji.TigerApp.protobuf.RoutePointOrBuilder getWaypointsOrBuilder(
      int index);
}
