// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VehicleStatus.proto

package com.dji.TigerApp.protobuf;

public interface VehicleAttitudeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.VehicleAttitude)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double pitch = 1;</code>
   * @return The pitch.
   */
  double getPitch();

  /**
   * <code>double yaw = 2;</code>
   * @return The yaw.
   */
  double getYaw();

  /**
   * <code>double roll = 3;</code>
   * @return The roll.
   */
  double getRoll();
}
