// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VehicleStatus.proto

package com.dji.TigerApp.protobuf;

public interface VehicleStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.VehicleStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.tutorial.Location location = 1;</code>
   * @return Whether the location field is set.
   */
  boolean hasLocation();
  /**
   * <code>.tutorial.Location location = 1;</code>
   * @return The location.
   */
  com.dji.TigerApp.protobuf.Location getLocation();
  /**
   * <code>.tutorial.Location location = 1;</code>
   */
  com.dji.TigerApp.protobuf.LocationOrBuilder getLocationOrBuilder();

  /**
   * <code>.tutorial.VehicleVelocity velocityXYZ = 2;</code>
   * @return Whether the velocityXYZ field is set.
   */
  boolean hasVelocityXYZ();
  /**
   * <code>.tutorial.VehicleVelocity velocityXYZ = 2;</code>
   * @return The velocityXYZ.
   */
  com.dji.TigerApp.protobuf.VehicleVelocity getVelocityXYZ();
  /**
   * <code>.tutorial.VehicleVelocity velocityXYZ = 2;</code>
   */
  com.dji.TigerApp.protobuf.VehicleVelocityOrBuilder getVelocityXYZOrBuilder();

  /**
   * <code>.tutorial.VehicleAttitude attitude = 3;</code>
   * @return Whether the attitude field is set.
   */
  boolean hasAttitude();
  /**
   * <code>.tutorial.VehicleAttitude attitude = 3;</code>
   * @return The attitude.
   */
  com.dji.TigerApp.protobuf.VehicleAttitude getAttitude();
  /**
   * <code>.tutorial.VehicleAttitude attitude = 3;</code>
   */
  com.dji.TigerApp.protobuf.VehicleAttitudeOrBuilder getAttitudeOrBuilder();

  /**
   * <code>string status = 4;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 4;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
