// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route.proto

package com.tiger;

public interface RouteArrayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.RouteArray)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tutorial.RoutePoint waypoints = 1;</code>
   */
  java.util.List<com.tiger.RoutePoint> 
      getWaypointsList();
  /**
   * <code>repeated .tutorial.RoutePoint waypoints = 1;</code>
   */
  com.tiger.RoutePoint getWaypoints(int index);
  /**
   * <code>repeated .tutorial.RoutePoint waypoints = 1;</code>
   */
  int getWaypointsCount();
  /**
   * <code>repeated .tutorial.RoutePoint waypoints = 1;</code>
   */
  java.util.List<? extends com.tiger.RoutePointOrBuilder> 
      getWaypointsOrBuilderList();
  /**
   * <code>repeated .tutorial.RoutePoint waypoints = 1;</code>
   */
  com.tiger.RoutePointOrBuilder getWaypointsOrBuilder(
      int index);
}
