// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route.proto

package com.tiger;

/**
 * Protobuf type {@code tutorial.RouteArray}
 */
public final class RouteArray extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tutorial.RouteArray)
    RouteArrayOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RouteArray.newBuilder() to construct.
  private RouteArray(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RouteArray() {
    waypoints_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RouteArray();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tiger.Route.internal_static_tutorial_RouteArray_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tiger.Route.internal_static_tutorial_RouteArray_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tiger.RouteArray.class, com.tiger.RouteArray.Builder.class);
  }

  public static final int WAYPOINTS_FIELD_NUMBER = 1;
  private java.util.List<com.tiger.RoutePoint> waypoints_;
  /**
   * <code>repeated .tutorial.RoutePoint waypoints = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.tiger.RoutePoint> getWaypointsList() {
    return waypoints_;
  }
  /**
   * <code>repeated .tutorial.RoutePoint waypoints = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.tiger.RoutePointOrBuilder> 
      getWaypointsOrBuilderList() {
    return waypoints_;
  }
  /**
   * <code>repeated .tutorial.RoutePoint waypoints = 1;</code>
   */
  @java.lang.Override
  public int getWaypointsCount() {
    return waypoints_.size();
  }
  /**
   * <code>repeated .tutorial.RoutePoint waypoints = 1;</code>
   */
  @java.lang.Override
  public com.tiger.RoutePoint getWaypoints(int index) {
    return waypoints_.get(index);
  }
  /**
   * <code>repeated .tutorial.RoutePoint waypoints = 1;</code>
   */
  @java.lang.Override
  public com.tiger.RoutePointOrBuilder getWaypointsOrBuilder(
      int index) {
    return waypoints_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < waypoints_.size(); i++) {
      output.writeMessage(1, waypoints_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < waypoints_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, waypoints_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tiger.RouteArray)) {
      return super.equals(obj);
    }
    com.tiger.RouteArray other = (com.tiger.RouteArray) obj;

    if (!getWaypointsList()
        .equals(other.getWaypointsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getWaypointsCount() > 0) {
      hash = (37 * hash) + WAYPOINTS_FIELD_NUMBER;
      hash = (53 * hash) + getWaypointsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tiger.RouteArray parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tiger.RouteArray parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tiger.RouteArray parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tiger.RouteArray parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tiger.RouteArray parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tiger.RouteArray parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tiger.RouteArray parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tiger.RouteArray parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tiger.RouteArray parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tiger.RouteArray parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tiger.RouteArray parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tiger.RouteArray parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tiger.RouteArray prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tutorial.RouteArray}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tutorial.RouteArray)
      com.tiger.RouteArrayOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tiger.Route.internal_static_tutorial_RouteArray_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tiger.Route.internal_static_tutorial_RouteArray_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tiger.RouteArray.class, com.tiger.RouteArray.Builder.class);
    }

    // Construct using com.tiger.RouteArray.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (waypointsBuilder_ == null) {
        waypoints_ = java.util.Collections.emptyList();
      } else {
        waypoints_ = null;
        waypointsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tiger.Route.internal_static_tutorial_RouteArray_descriptor;
    }

    @java.lang.Override
    public com.tiger.RouteArray getDefaultInstanceForType() {
      return com.tiger.RouteArray.getDefaultInstance();
    }

    @java.lang.Override
    public com.tiger.RouteArray build() {
      com.tiger.RouteArray result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tiger.RouteArray buildPartial() {
      com.tiger.RouteArray result = new com.tiger.RouteArray(this);
      int from_bitField0_ = bitField0_;
      if (waypointsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          waypoints_ = java.util.Collections.unmodifiableList(waypoints_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.waypoints_ = waypoints_;
      } else {
        result.waypoints_ = waypointsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tiger.RouteArray) {
        return mergeFrom((com.tiger.RouteArray)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tiger.RouteArray other) {
      if (other == com.tiger.RouteArray.getDefaultInstance()) return this;
      if (waypointsBuilder_ == null) {
        if (!other.waypoints_.isEmpty()) {
          if (waypoints_.isEmpty()) {
            waypoints_ = other.waypoints_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureWaypointsIsMutable();
            waypoints_.addAll(other.waypoints_);
          }
          onChanged();
        }
      } else {
        if (!other.waypoints_.isEmpty()) {
          if (waypointsBuilder_.isEmpty()) {
            waypointsBuilder_.dispose();
            waypointsBuilder_ = null;
            waypoints_ = other.waypoints_;
            bitField0_ = (bitField0_ & ~0x00000001);
            waypointsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getWaypointsFieldBuilder() : null;
          } else {
            waypointsBuilder_.addAllMessages(other.waypoints_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.tiger.RoutePoint m =
                  input.readMessage(
                      com.tiger.RoutePoint.parser(),
                      extensionRegistry);
              if (waypointsBuilder_ == null) {
                ensureWaypointsIsMutable();
                waypoints_.add(m);
              } else {
                waypointsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.tiger.RoutePoint> waypoints_ =
      java.util.Collections.emptyList();
    private void ensureWaypointsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        waypoints_ = new java.util.ArrayList<com.tiger.RoutePoint>(waypoints_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.tiger.RoutePoint, com.tiger.RoutePoint.Builder, com.tiger.RoutePointOrBuilder> waypointsBuilder_;

    /**
     * <code>repeated .tutorial.RoutePoint waypoints = 1;</code>
     */
    public java.util.List<com.tiger.RoutePoint> getWaypointsList() {
      if (waypointsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(waypoints_);
      } else {
        return waypointsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tutorial.RoutePoint waypoints = 1;</code>
     */
    public int getWaypointsCount() {
      if (waypointsBuilder_ == null) {
        return waypoints_.size();
      } else {
        return waypointsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tutorial.RoutePoint waypoints = 1;</code>
     */
    public com.tiger.RoutePoint getWaypoints(int index) {
      if (waypointsBuilder_ == null) {
        return waypoints_.get(index);
      } else {
        return waypointsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tutorial.RoutePoint waypoints = 1;</code>
     */
    public Builder setWaypoints(
        int index, com.tiger.RoutePoint value) {
      if (waypointsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWaypointsIsMutable();
        waypoints_.set(index, value);
        onChanged();
      } else {
        waypointsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.RoutePoint waypoints = 1;</code>
     */
    public Builder setWaypoints(
        int index, com.tiger.RoutePoint.Builder builderForValue) {
      if (waypointsBuilder_ == null) {
        ensureWaypointsIsMutable();
        waypoints_.set(index, builderForValue.build());
        onChanged();
      } else {
        waypointsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.RoutePoint waypoints = 1;</code>
     */
    public Builder addWaypoints(com.tiger.RoutePoint value) {
      if (waypointsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWaypointsIsMutable();
        waypoints_.add(value);
        onChanged();
      } else {
        waypointsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.RoutePoint waypoints = 1;</code>
     */
    public Builder addWaypoints(
        int index, com.tiger.RoutePoint value) {
      if (waypointsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWaypointsIsMutable();
        waypoints_.add(index, value);
        onChanged();
      } else {
        waypointsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.RoutePoint waypoints = 1;</code>
     */
    public Builder addWaypoints(
        com.tiger.RoutePoint.Builder builderForValue) {
      if (waypointsBuilder_ == null) {
        ensureWaypointsIsMutable();
        waypoints_.add(builderForValue.build());
        onChanged();
      } else {
        waypointsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.RoutePoint waypoints = 1;</code>
     */
    public Builder addWaypoints(
        int index, com.tiger.RoutePoint.Builder builderForValue) {
      if (waypointsBuilder_ == null) {
        ensureWaypointsIsMutable();
        waypoints_.add(index, builderForValue.build());
        onChanged();
      } else {
        waypointsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.RoutePoint waypoints = 1;</code>
     */
    public Builder addAllWaypoints(
        java.lang.Iterable<? extends com.tiger.RoutePoint> values) {
      if (waypointsBuilder_ == null) {
        ensureWaypointsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, waypoints_);
        onChanged();
      } else {
        waypointsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.RoutePoint waypoints = 1;</code>
     */
    public Builder clearWaypoints() {
      if (waypointsBuilder_ == null) {
        waypoints_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        waypointsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.RoutePoint waypoints = 1;</code>
     */
    public Builder removeWaypoints(int index) {
      if (waypointsBuilder_ == null) {
        ensureWaypointsIsMutable();
        waypoints_.remove(index);
        onChanged();
      } else {
        waypointsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.RoutePoint waypoints = 1;</code>
     */
    public com.tiger.RoutePoint.Builder getWaypointsBuilder(
        int index) {
      return getWaypointsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tutorial.RoutePoint waypoints = 1;</code>
     */
    public com.tiger.RoutePointOrBuilder getWaypointsOrBuilder(
        int index) {
      if (waypointsBuilder_ == null) {
        return waypoints_.get(index);  } else {
        return waypointsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tutorial.RoutePoint waypoints = 1;</code>
     */
    public java.util.List<? extends com.tiger.RoutePointOrBuilder> 
         getWaypointsOrBuilderList() {
      if (waypointsBuilder_ != null) {
        return waypointsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(waypoints_);
      }
    }
    /**
     * <code>repeated .tutorial.RoutePoint waypoints = 1;</code>
     */
    public com.tiger.RoutePoint.Builder addWaypointsBuilder() {
      return getWaypointsFieldBuilder().addBuilder(
          com.tiger.RoutePoint.getDefaultInstance());
    }
    /**
     * <code>repeated .tutorial.RoutePoint waypoints = 1;</code>
     */
    public com.tiger.RoutePoint.Builder addWaypointsBuilder(
        int index) {
      return getWaypointsFieldBuilder().addBuilder(
          index, com.tiger.RoutePoint.getDefaultInstance());
    }
    /**
     * <code>repeated .tutorial.RoutePoint waypoints = 1;</code>
     */
    public java.util.List<com.tiger.RoutePoint.Builder> 
         getWaypointsBuilderList() {
      return getWaypointsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.tiger.RoutePoint, com.tiger.RoutePoint.Builder, com.tiger.RoutePointOrBuilder> 
        getWaypointsFieldBuilder() {
      if (waypointsBuilder_ == null) {
        waypointsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.tiger.RoutePoint, com.tiger.RoutePoint.Builder, com.tiger.RoutePointOrBuilder>(
                waypoints_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        waypoints_ = null;
      }
      return waypointsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tutorial.RouteArray)
  }

  // @@protoc_insertion_point(class_scope:tutorial.RouteArray)
  private static final com.tiger.RouteArray DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tiger.RouteArray();
  }

  public static com.tiger.RouteArray getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RouteArray>
      PARSER = new com.google.protobuf.AbstractParser<RouteArray>() {
    @java.lang.Override
    public RouteArray parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RouteArray> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RouteArray> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tiger.RouteArray getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

