// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route.proto

package com.tiger;

public interface RoutePointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.RoutePoint)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double lat = 1;</code>
   * @return The lat.
   */
  double getLat();

  /**
   * <code>double long = 2;</code>
   * @return The long.
   */
  double getLong();

  /**
   * <code>double alt = 3;</code>
   * @return The alt.
   */
  double getAlt();

  /**
   * <code>float speed = 4;</code>
   * @return The speed.
   */
  float getSpeed();
}
