// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route.proto

package com.tiger;

public final class Route {
  private Route() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_RoutePoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_RoutePoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_RouteArray_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_RouteArray_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013route.proto\022\010tutorial\"C\n\nRoutePoint\022\013\n" +
      "\003lat\030\001 \001(\001\022\014\n\004long\030\002 \001(\001\022\013\n\003alt\030\003 \001(\001\022\r\n" +
      "\005speed\030\004 \001(\002\"5\n\nRouteArray\022\'\n\twaypoints\030" +
      "\001 \003(\0132\024.tutorial.RoutePointB\r\n\tcom.tiger" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_RoutePoint_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_RoutePoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_RoutePoint_descriptor,
        new java.lang.String[] { "Lat", "Long", "Alt", "Speed", });
    internal_static_tutorial_RouteArray_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_RouteArray_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_RouteArray_descriptor,
        new java.lang.String[] { "Waypoints", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
